copyright: 2008-2010 Yaroslaff Fedin http://orwik.com/people/inviz
authors: Orwik team, http://developers.orwik.com
files:
  - "Source/Widget/Widget.js" #files to extend
  - "Source/Widget/Input/Input.js" 
  - "Source/Library/Inflections" #new file